apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-eric-cluster3
  namespace: test-tmc
spec:
  distribution:
    version: v1.18.5+vmware.1-tkg.1.c40d30d # v1.20.7+vmware.1-tkg.1.7fb9067
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu
    workers:
      count: 3
      class: best-effort-small
      storageClass: tanzu
      